version: '3.4'

services:
  postgresDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  mongoDB:
    image: mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"

  redisDB:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    env_file:
      .env
    depends_on:
      - postgresDB
      - mongoDB
      - redisDB
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
